---

- hosts: '{{ hostip }}'
  gather_facts: False
  become: yes

  tasks:
    - name: Set the hostname
      hostname: name={{ hostname }}

    - name: add myself to /etc/hosts
      lineinfile:
        dest: /etc/hosts
        line: '127.0.0.1   {{ hostname }}'

    - name: Set hostname
      shell: 'hostname {{ hostname }}'
